apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config
data:
  config.json: |
    {
        "roses": "red",
        "violets": "blue",
        "foo": "something",
        "bar": true
    }
  message.txt: |
    hello world!
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
  - name: config
    configMap:
      name: kuard-config
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    volumeMounts:
    - name: config
      mountPath: /config
