apiVersion: v1
kind: Pod
metadata:
  name: kuard-0
  labels:
    app: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 2
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-1
  labels:
    app: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 2
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-2
  labels:
    app: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 2
      timeoutSeconds: 1
      periodSeconds: 5
      failureThreshold: 3
